version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "nette/di"
      - dependency-name: "nette/schema"
      - dependency-name: "nette/bootstrap"
      - dependency-name: "nette/neon"
    groups:
        phpstan:
            patterns: ["*phpstan*"]
